"""empty message

Revision ID: 56a10505f529
Revises: 0763d677d453
Create Date: 2025-11-12 10:56:38.021932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a10505f529'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('s_api_key', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['s_api_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('s_api_key')

    # ### end Alembic commands ###
